### ISSUE TITLE
installation docs

### ISSUE THREAD

**Issue by tkphd** [hpc-carpentry/amdahl#4]
It looks like there are a few different ways to install & use this library. Can you add a section to README with the "recommended" installation instructions?

**Comment by ocaisa** [comment]
This is a bit tricky because this is a plain python package without anything special inside. Since it is a simple python package lot's of tools like EasyBuild, Spack, and Conda can deal with it in a straightforward way and that leads to the options as regards installation. However, none of the recipes for those tools are included here, so using them already assumes that you are pretty well versed in them.

You can let those tools set things up for you, or you can simply do `pip install --user amdahl` which will work as long as `mpi4py` is available at install time.
